### ISSUE TITLE
**コンポーネント作成**

### ISSUE THREAD

**Issue by Tatsuya324** [jphacks/C_2002#2]
フロント再度のコンポーネント作成を行っていく
- [x] App.vue
- [x] ChatTree.vue
- [x] Preview.vue

**Comment by Tatsuya324** [comment]
通常メールのサイドバーの項目は基本できに入力が完了してると思う

**Comment by Tatsuya324** [comment]
あとはメールのプレビューコンポーネントだ
参考にするのはGmailか何にしようかな

**Comment by ree-rishun** [comment]
今、作ってくれた部分みているんだけど、borderの設定方法が気になったから一応指摘しておく（コピペなら無視して）
```css
        border: solid 2px;
        border-color: #aaaaaa;
```
こんな風に指定されていたけど、
```css
        border: solid 2px #aaaaaa;
```
こんな風に1行で出来るからこれでやって欲しい。
極力同じスタイルに対する値は1か所にまとめてもらえると見やすくていいかと・・・

ちなみに修正はしておいたので、次回以降気にしてもらえればOK

**Comment by Tatsuya324** [comment]
了解です。
知りませんでした
あざます

**Comment by ree-rishun** [comment]
SCSSの書き方だけど、HTMLみたいに全てを階層化する必要はないと思う！
こんな感じだけど、
```scss
app{
  frame{
    message{
        name{}
        title{}
    }
  }
}
```
こんな感じにするのが良いかと
```scss
app{
}
frame{

}
message{
  name{}
  title{}
}
```
HTML階層に囚われずにパーツ単位でSCSSの階層を使うと、別の階層でのパーツの再利用も可能になるからオススメかな！

**Comment by Tatsuya324** [comment]
再利用を考えてなかったすね
今後意識してSCSSの作り直しがいるかもですね

**Comment by ree-rishun** [comment]
ひとまず、デザインを変更しつつSCSSの構造や書き方も少しずつ修正しているので、参考にしてもらえればと！
まぁ、ハッカソンなので細かいこと言うつもりはないけど、せっかくなのでアドバイスとして受け取ってもらえればと！
