### ISSUE TITLE
メール受信処理の実装

### ISSUE THREAD

**Issue by ree-rishun** [jphacks/C_2002#25]
メールの受信部分を実装

**Comment by ree-rishun** [comment]
@rappy-git 
この辺が参考になれば参考にして欲しい
https://liginc.co.jp/web/service/facebook/153850/2
https://qiita.com/ekzemplaro/items/a7d4bfa7a75fc6c661b3
https://sendgrid.kke.co.jp/blog/?p=7648

**Comment by ree-rishun** [comment]
@rappy-git 
Electronのやつ
https://qiita.com/hitenkoku/items/c2ffb868a8d4ecd39486

**Comment by ree-rishun** [comment]
メールヘッダ内容の一覧
https://www.atmarkit.co.jp/fnetwork/rensai/netpro03/mail-header.html

**Comment by ree-rishun** [comment]
今から取り掛かる。

**Comment by Tatsuya324** [comment]
Slack見てないかもですけど，プルしてからオナしゃす

**Comment by ree-rishun** [comment]
ひとまず、諸々のエラーは解決した。
iconvでエラーが出る場合は以下を参照。
https://qiita.com/odorry/items/09c9abef6c99ec55486f

てか、inbox -> iconv でメールの本文のみが取得できると思ってたけど、実際はメールの全体が文字列として取得できるだけだった。
またパーサー作るのかよ…

**Comment by ree-rishun** [comment]
ひとまずメールの受信自体はできるので閉じ
