### ISSUE TITLE
メール送信処理の実装

### ISSUE THREAD

**Issue by ree-rishun** [jphacks/C_2002#36]

**Comment by ree-rishun** [comment]
## 利用ライブラリ

- nodemailer

## 参考サイト

[速攻NodeJSで簡単メール送信 - Qiita](https://qiita.com/kashih/items/59e1c0a8c3b1e483ecbe)

**Comment by ree-rishun** [comment]
@TatsuyaOkazaki324 
メールの送受信のためにユーザ情報の管理ファイルを作成したいんだけど、パスってもう決まってたっけ？
ちなみにJSONファイルで管理したい。

**Comment by ree-rishun** [comment]
Qiitaのサンプルコードでは情報が不足しているので公式ドキュメントへGo
https://nodemailer.com/about/
ロゴがKotlinみある。

**Comment by Tatsuya324** [comment]
えーと決まってはないですけど，暫定的にメールアドレスとPWを格納してるのは，

`Home(OS依存)/FrankFurt/userInformation.json`

かと思います．メアドとPWは分けた方がいいかと思うので，コードの名称を変えないとですね

**Comment by ree-rishun** [comment]
> メアドとPWは分けた方がいいかと思うので，コードの名称を変えないとですね

これはファイル自体を分けた方が良いという話なのかな？
ファイルは一緒でいいような気もするけど

```
auth: {
  mail: 'test@example.com',
  pass: '暗号化されたやつ？'
}
```
とかでいいのかな？と
ただ、最終的にSMTPへパスワードを渡す段階で平文のパスワードが必要になるんだよなぁ…

**Comment by ree-rishun** [comment]
今考えている案としては、パスワードを分割するアルゴリズムを作成して、

- パスワード登録時に2つのデータに分割
- 片割れをDBに保存
- 片割れをローカルに保存
- 認証時にDBから片割れを引っ張ってきてローカルで結合

ってのが安全なのかな？と…
分割って前半後半とかじゃなく1byte毎に、4bitをローカル/4bitをDBみたいな感じで分割していくイメージ。
まぁ、最悪平文だな。

**Comment by Tatsuya324** [comment]
その処理もいいかもですけど，OS依存で文字コードの処理が変わるかもしれないんで，普通に，ローカルの環境変数とかそこらへんの値を一個持ってきて，そんだけぶん文字コードをシフトするみたいな処理でもいい気がします．セキュアかどうかは分かりませんが，機種依存のエラーはないかと

**Comment by Tatsuya324** [comment]
> これはファイル自体を分けた方が良いという話なのかな？

その解釈であってます
ただ，同じファイルにいろんなデータが入るなら，現状上書き処理になってるのでそれをどうにかしないといけません

**Comment by ree-rishun** [comment]
> ただ，同じファイルにいろんなデータが入るなら，現状上書き処理になってるのでそれをどうにかしないといけません

上書は頻繁に行われる訳じゃないし、

1. JSONを取得してObjectに格納
2. Objectの内容を編集
3. Objectの内容をJSON形式で上書き

って感じなら楽に行けそう？まぁ、追々実装しよう（てかしといて

[JSON→Object](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse)
[Object→JSON](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify)

**Comment by Tatsuya324** [comment]
まあ処理的にはチェックして編集するだけなんで簡単ですね．
いい感じに実装しておきます

**Comment by ree-rishun** [comment]
JSON、SMTP周りの情報はこんな感じにして欲しい
```
{
          host: 'smtp.gmail.com',
          port: 465,
          secure: true,
          auth: {
            user: 'example@gmail.com',
            pass: 'password'
          }
        }
```
Tabが変なのは許せ

**Comment by ree-rishun** [comment]
DONE速報
- メール送信ボタンの実装
- nodemailerを利用したメール送信
- JSONからSMTP情報を取得してのメール送信
