### ISSUE TITLE
メール内容のGit管理

### ISSUE THREAD

**Issue by ree-rishun** [jphacks/C_2002#37]

**Comment by ree-rishun** [comment]
## 実装できた部分

- 改行されるごとに入力された文章を下書きファイルへ保存
- 下書きファイルの内容をGitにて管理
- Gitで取得した差分はAPIにPOSTされて戻ってきた値を変換結果管理ファイルへ保存（こっちのファイルはGit管理なし）

## 実装できていない部分（バグ）

- 末尾行を削除すると余分な行も削除されてしまう
- 行削除後の行追加が動いて無さそうなので、行単位の更新もできていないかも？
- 空白行の取り扱いができていない

## 簡単に言うと…

メールを書くだけなら実装できたが、文章を削除したりするとバグが発生する。

**Comment by Tatsuya324** [comment]
バグの発生の仕方的に綺麗じゃないかもしれないですけど，Enterを押されたときの文字数をカウントして処理を分岐すればなんとかなりませんかね？
そういうことじゃないってならすみませんw

**Comment by ree-rishun** [comment]
一応それは実装しているんだけど、今回も同期・非同期周りの問題かもしれない
なんとなく原因は分かっているから後々対処するつもり
正直、GitでなくJSで文字数とか見て管理するならもうとっくに終わってたけど、せっかくGit使ったと言い張る以上極力Gitで管理したいんよねぇ…

**Comment by Tatsuya324** [comment]
原因がわかってそうならあれですけど，行番号で処理をしてるんでしたっけ？
その行番号の概念が例えば「i 行削除すると」行の位置は「- i された位置」に行くってのがある気がするので，そこらへんが問題になってそうですね

**Comment by ree-rishun** [comment]
原因なんだけど
X行が変更された場合にGitでは
- X行は1行まるまる削除された
- X行が追加された（変更後の内容）
っていう風な扱いになるんよ

だから、処理も自然と
- X行を削除
- X行を追加（変更後の内容を）
ってやっているんだけど、X行を追加する際に同期がズレて先に追加が行われて後から削除されていそうな雰囲気なんだよね…わからんけど。

**Comment by ree-rishun** [comment]
改行・削除キーが押されたときに発火する処理が完成
