### ISSUE TITLE
メールサービス一覧用のアイコン画像取得

### ISSUE THREAD

**Issue by ree-rishun** [jphacks/C_2002#43]
## 格納先

```
front/src/renderer/aseets/img/
```

## 利用規約の確認

企業によって、
- 縦横に〇pxの余白が必要
- 背景色には #xxxxxxx を利用
みたいなロゴを使う上での規約があると思うので、それを調べて欲しい！

調べた内容はIssueに！

**Comment by Tatsuya324** [comment]
## [Google](https://sites.google.com/a/googleapps.com/deploy-google-apps-ja-3/Home/user-resources/google-icons-and-logos)

### 禁止事項

[ガイドライン](Google ページ（https://sites.google.com/a/googleapps.com/deploy-google-apps-ja-3/Home/user-resources/google-icons-and-logos/guidelines-for-using-google-brand-features)
-  Google ブランドを部分的に削除、変形、改造しない 
- Google ページ（Google ロゴや Google 検索ボックスをクリックして表示されるページを含む）をフレーム処理、ミラー処理しない

## [Yahoo](https://about.yahoo.co.jp/common/copyright/)

### Y! は[申請](https://forms.business.yahoo.co.jp/webform/Inquiry/InquiryTop?inquiry_type=pr_inquiry_9842)が必要

**Comment by ree-rishun** [comment]
@TatsuyaOkazaki324 
あ、ごめん説明不足で
これ石倉君にお願いしてある

**Comment by ree-rishun** [comment]
@rappy-git 
gmailとY!は調べてもらったので他をお願いします〜

**Comment by ree-rishun** [comment]
## Yahoo
デベロッパー向けのガイドラインはこちら
https://developer.yahoo.co.jp/yconnect/loginbuttons.html

**Comment by ree-rishun** [comment]
## アイコン画像格納位置の変更

`front/src/renderer/assets/img/mail_icons/`
アイコン画像自体はこちらにお願いします！


## 格納して欲しいアイコン

- [x] gmail
- [x] Yahoo
- [x] Outlook
- [x] iCloud


## アイコン画像のガイドラインの確認

- [x] gmail
- [x] Yahoo
- [x] Outlook
- [x] iCloud

終わってない部分のみお願いします。
ガイドラインはIssueに貼ってってください（URLでも可）

**Comment by rpyjp** [comment]
マイクロソフト商標ガイドライン (一般ガイドライン) (英文)
https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/general

**Comment by rpyjp** [comment]
Apple商標および著作権使用に関するガイドライン
https://www.apple.com/jp/legal/intellectual-property/guidelinesfor3rdparties.html

**Comment by ree-rishun** [comment]
問題ないので閉じます！
@rappy-git 
ありがとう！
