### ISSUE TITLE
認証情報登録画面の作成

### ISSUE THREAD

**Issue by ree-rishun** [jphacks/C_2002#45]
最初に認証情報を登録したりその後も変更等を加えるための画面の作成

**Comment by ree-rishun** [comment]
@TatsuyaOkazaki324 
`front/src/renderer/aseets/json/MailAuth.json` にメールの基本情報があるので、

- 開いた画面でメールサービス一覧を表示（その他も）
- メールサービスを選択した場合はアカウント情報のみを取得↓
  - メールアドレス
  - パスワード
- その他の場合は、SMTPやIMAP(or POP)も入力してもらう

みたいな感じで実装するとよさげかと！
実装お願いします！

**Comment by Tatsuya324** [comment]
環境壊れててすぐに対応できなさそうなんで出来次第
別コンポーネントで実装しますね

ここで入力されたデータの格納場所を教えて欲しいんですけど
` Home/frankfurt/data/ `
のどっかに入れますか？

**Comment by ree-rishun** [comment]
昨日作ってたJSONファイルでいいよ！
今利用しているのはこんな感じになった！
```
{
  "smtp": {
    "host": "smtp.gmail.com",
    "port": 465,
    "secure": true
  },
  "imap": {
    "host": "imap.gmail.com",
    "port": "993"
  },
  "pop": {
    "host": "pop.gmail.com",
    "port": "995"
  },
  "user": {
    "name": "ReERishun",
    "affiliation": "株式会社PiedPiper"
  },
  "auth": {
    "user": "mail@gmail.com",
    "pass": "password"
  }
}
```

**Comment by Tatsuya324** [comment]
imap と pop ってスイッチできるようにしますか？

**Comment by ree-rishun** [comment]
それが理想やな！
